"""Generate the distributable skill's rule catalog from ``rules.RULES``.

The catalog under ``skills/planlint-spec-governance/references/`` is a
*generated* file, never hand-edited. This repo already carries a guard
(``tests/test_rule_registry_docs.py``) that exists because a hand-maintained
copy of the rule table drifted three separate times; a fourth copy inside the
skill would reproduce that exact class of bug, and a skill that cites a rule
id or severity the engine no longer has is worse than one that cites none
(DEC-SD-002).

Unlike most ``tools/`` gate scripts, this one imports ``openspec_graph`` --
the same deliberate exception ``tools/render_mermaid.py`` documents, and for
the same reason: the alternative is re-deriving the registry's contents here,
which is the duplication this script exists to remove. It therefore relies on
the project being installed (``pip install -e .``), exactly as ``make test``
and CI already require.

Deliberately prints **no rule count**. ``tests/test_rule_registry_docs.py``
matches rule rows only inside ``README.md`` and a count claim in four named
documents, so a total printed here would be the one number in the repository
that could drift with nothing checking it (DEC-SD-003).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from openspec_graph.rules import RULES

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = (
    REPO_ROOT / "skills" / "planlint-spec-governance" / "references" / "rule-catalog.md"
)

_HEADER = """<!-- GENERATED by tools/render_rule_catalog.py -- do not edit by hand. -->
<!-- Regenerate with: make skill-catalog -->

# planlint rule catalog

Every rule the engine can report, generated from the rule registry itself.
`planlint rules --json` prints the same data from an installed CLI, which is
the authoritative source at run time; this file exists so an agent can read
the catalog without executing anything.

Dialect `any` means the rule applies to every dialect.

| ID | Sev | Dialects | Checks |
|---|---|---|---|
"""


def render() -> str:
    """Return the catalog markdown for the current rule registry.

    Pure: takes no arguments, touches no filesystem, and depends only on
    ``RULES``, so the output is byte-stable for a given registry (mirrors the
    determinism contract every other derived-output module here holds).
    """
    rows = []
    for rule in RULES:
        dialects = "any" if "*" in rule.dialects else ", ".join(rule.dialects)
        rows.append(f"| {rule.ident} | {rule.severity} | {dialects} | {rule.summary} |")
    return _HEADER + "\n".join(rows) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="regenerate the catalog file")
    group.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the catalog on disk is stale or missing",
    )
    args = parser.parse_args(argv)

    expected = render()
    if args.write:
        CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        CATALOG_PATH.write_text(expected, encoding="utf-8")
        print(f"wrote {CATALOG_PATH.relative_to(REPO_ROOT).as_posix()}")
        return 0

    if not CATALOG_PATH.exists():
        print(
            f"STALE: {CATALOG_PATH.relative_to(REPO_ROOT).as_posix()} does not exist; "
            "run `make skill-catalog`",
            file=sys.stderr,
        )
        return 1
    actual = CATALOG_PATH.read_text(encoding="utf-8")
    if actual != expected:
        print(
            f"STALE: {CATALOG_PATH.relative_to(REPO_ROOT).as_posix()} does not match "
            "the rule registry; run `make skill-catalog`",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
